SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
TILE_SIZE = 40
TILES_X = SCREEN_WIDTH / TILE_SIZE
TILES_Y = SCREEN_HEIGHT / TILE_SIZE
GRID_COLOR = 0x33ffffff
WALL_COLOR = 0xffffffff
MARK_COLOR = {
  circle: 0x3333cc,
  x: 0xcc3333,
  square: 0xffffff,
}.freeze
DEFAULT_TEXT_COLOR = 0xffffff
L_S_MAX_ZOOM = 4
